spring:
  redis:
    host: 192.168.1.50
    database: 9
    port: 6379
    password: bizvane
    jedis:
      pool:
        max-active: 100
        max-idle: 8
        max-wait: 2000ms
        min-idle: 0