server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fast-s?useUnicode=true&characterEncoding=utf-8
    username: root
    password: dingshichen
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml
  type-aliases-package: cn.dsc.security.model.po
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl