spring:
  datasource:
    url: jdbc:mysql://bizvane-2018.mysql.polardb.rds.aliyuncs.com:3306/fast-s?useUnicode=true&characterEncoding=utf-8
    username: bizvane_2018
    password: SF_bizvane20180613
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml