server:
  port: 8080
spring:
  kafka:
    bootstrap-servers: 119.29.41.244:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all

