server:
  port: 8088
shardingmini:
  datasources:
    _default:
      url: jdbc:mysql://127.0.0.1:3306/fast_mall?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
      username: root
      password: dingshichen
      driver-class-name: com.mysql.cj.jdbc.Driver