spring:
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/fast_mall?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: dingshichen
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
mybatis:
#  type-aliases-package: cn.dsc.p6spy.entity
  mapper-locations: classpath:mybatis/*Mapper.xml