spring:
  shardingsphere:
    datasource:
      names: master,slave1
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/sharding-1
        username: root
        password: dingshichen
      slave1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/sharding-2
        username: root
        password: dingshichen
mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml
  type-aliases-package: cn.dsc.shardingjdbc.entity